//! `server.json` — one MCP server's frozen shape — and the two layers that hold
//! its secrets.
//!
//! The SHAPE (the command, its arguments, the NAMES of the variables the server
//! needs, and which exposed tool means which of the server's) is frozen into the
//! generated package's snapshot, so changing any of it is a new version.
//!
//! The VALUES are never in there. A version directory is content-addressed and
//! world-readable, and the host strips secret-shaped variables out of an
//! extension's environment before it starts — so a token reaches the server only
//! through a file this package reads itself, in one of two directories the
//! kernel knows nothing about. Nearest wins, whole: the file that answers is one
//! file, so nobody has to reason about half a credential coming from each layer.

const std = @import("std");

/// One exposed tool, and the server tool it stands for. Explicit rather than
/// derived by stripping the prefix: an MCP name may hold characters an
/// extension tool name may not, so the exposed name is not always reversible.
pub const ToolMap = struct {
    name: []const u8,
    tool: []const u8,
};

pub const Spec = struct {
    /// The format of this file, so a package generated by an older mcp is read
    /// as what it is rather than guessed at.
    v: u32 = 1,
    /// The server's short name: the id suffix, the tool-name prefix, and the
    /// stem of the configuration file that carries its secrets.
    name: []const u8,
    command: []const u8 = "",
    args: []const []const u8 = &.{},
    /// The environment variable NAMES this server needs. Values live in the two
    /// layers below; a name with no value is a failed call, not a silent spawn.
    env: []const []const u8 = &.{},
    tools: []const ToolMap = &.{},

    /// The server's own name for an exposed tool, or null when this package
    /// does not expose it.
    pub fn serverTool(self: Spec, exposed: []const u8) ?[]const u8 {
        for (self.tools) |t| {
            if (std.mem.eql(u8, t.name, exposed)) return t.tool;
        }
        return null;
    }
};

pub const format_version: u32 = 1;

/// The file's name inside the package's `src/`, so it rides the snapshot.
pub const spec_file = "server.json";

pub fn encode(alloc: std.mem.Allocator, spec: Spec) ![]u8 {
    return std.json.Stringify.valueAlloc(alloc, spec, .{ .whitespace = .indent_2 });
}

pub fn decode(alloc: std.mem.Allocator, bytes: []const u8) !Spec {
    return std.json.parseFromSliceLeaky(Spec, alloc, bytes, .{
        .ignore_unknown_fields = true,
        .allocate = .alloc_always,
    });
}

/// This binary's own frozen spec, or null when it has none.
///
/// A frozen extension binary sits at `<version>/bin/<entry>` and its frozen
/// sources at `<version>/package/src/`, so the spec is two directories up and
/// back down. Absence is not a fault: it is how the generator tells itself apart
/// from a package it generated.
pub fn besideExe(alloc: std.mem.Allocator, io: std.Io) !?Spec {
    const exe = std.process.executablePathAlloc(io, alloc) catch return null;
    const bin_dir = std.fs.path.dirname(exe) orelse return null;
    const version_dir = std.fs.path.dirname(bin_dir) orelse return null;
    const path = try std.fs.path.join(alloc, &.{ version_dir, "package", "src", spec_file });
    const bytes = std.Io.Dir.cwd().readFileAlloc(io, path, alloc, .limited(1 << 20)) catch return null;
    return try decode(alloc, bytes);
}

// ── the two layers ──────────────────────────────────────────────────────────

/// Where a server's secrets live, relative to the workspace (this process's cwd).
pub const project_dir = ".nulya" ++ std.fs.path.sep_str ++ "mcp";

/// This machine's directory: `$NULYA_HOME/mcp`, else `<home>/.nulya/mcp`. Null
/// when there is no home, which is a fact about the machine, not a failure.
pub fn userDir(alloc: std.mem.Allocator, env: *const std.process.Environ.Map) !?[]const u8 {
    if (env.get("NULYA_HOME")) |home| {
        if (home.len > 0) return try std.fs.path.join(alloc, &.{ home, "mcp" });
    }
    const home = env.get("HOME") orelse env.get("USERPROFILE") orelse return null;
    if (home.len == 0) return null;
    return try std.fs.path.join(alloc, &.{ home, ".nulya", "mcp" });
}

/// Both files a server's secrets may come from, in search order. Always at least
/// one, so a message can name somewhere to write.
pub fn candidates(alloc: std.mem.Allocator, env: *const std.process.Environ.Map, name: []const u8) ![]const []const u8 {
    var out: std.ArrayList([]const u8) = .empty;
    const file = try std.fmt.allocPrint(alloc, "{s}.json", .{name});
    try out.append(alloc, try std.fs.path.join(alloc, &.{ project_dir, file }));
    if (try userDir(alloc, env)) |dir| try out.append(alloc, try std.fs.path.join(alloc, &.{ dir, file }));
    return out.items;
}

/// The configuration that answered, with the path it came from so a refusal can
/// say which file it read rather than which files exist.
pub const Config = struct {
    path: []const u8,
    values: std.json.ObjectMap,

    pub fn get(self: Config, key: []const u8) ?[]const u8 {
        return switch (self.values.get(key) orelse return null) {
            .string => |s| s,
            else => null,
        };
    }
};

pub const LoadError = error{ Unreadable, NotAnObject } || std.mem.Allocator.Error;

/// The nearest layer's file, parsed. Null when neither layer has one.
///
/// A file that is there but is not `{"env": {…}}` is an ERROR rather than a
/// fallthrough: falling through would run the server on the other layer's
/// credentials while the person edits the file they believe is in effect. A file
/// that cannot be opened at all is the same as one that is not there — this
/// cannot tell "no such directory" from "no such file" on both platforms, and
/// the refusal names both paths either way.
pub fn load(
    alloc: std.mem.Allocator,
    io: std.Io,
    env: *const std.process.Environ.Map,
    name: []const u8,
) LoadError!?Config {
    for (try candidates(alloc, env, name)) |path| {
        const bytes = std.Io.Dir.cwd().readFileAlloc(io, path, alloc, .limited(1 << 20)) catch continue;
        const parsed = std.json.parseFromSliceLeaky(std.json.Value, alloc, bytes, .{}) catch return error.Unreadable;
        const obj = switch (parsed) {
            .object => |o| o,
            else => return error.NotAnObject,
        };
        const values = switch (obj.get("env") orelse std.json.Value{ .object = .empty }) {
            .object => |o| o,
            else => return error.NotAnObject,
        };
        return .{ .path = path, .values = values };
    }
    return null;
}

/// The declared variables this configuration does not supply, in declaration
/// order. Empty means the server can be started.
pub fn missing(alloc: std.mem.Allocator, spec: Spec, config: ?Config) ![]const []const u8 {
    var out: std.ArrayList([]const u8) = .empty;
    for (spec.env) |key| {
        const value = if (config) |c| c.get(key) else null;
        if (value == null or value.?.len == 0) try out.append(alloc, key);
    }
    return out.items;
}

/// What the model reads when a package is installed but not configured. It names
/// the variables, every file that would supply them, the shape of that file, and
/// the route to this package's own manual — the manual is versioned, so the
/// route is a command rather than a path that could go stale.
pub fn notConfiguredMessage(
    alloc: std.mem.Allocator,
    env: *const std.process.Environ.Map,
    spec: Spec,
    config: ?Config,
    absent: []const []const u8,
) ![]u8 {
    var out: std.Io.Writer.Allocating = .init(alloc);
    errdefer out.deinit();
    const w = &out.writer;

    try w.print("mcp.{s} is not configured: no value for ", .{spec.name});
    for (absent, 0..) |key, i| try w.print("{s}{s}", .{ if (i == 0) "" else ", ", key });
    if (config) |c| {
        try w.print(".\nRead from {s}; add the missing keys there", .{c.path});
    } else {
        try w.writeAll(".\nWrite them into the first of these files that you create");
    }
    try w.writeAll(":\n");
    for (try candidates(alloc, env, spec.name)) |path| try w.print("  {s}\n", .{path});
    try w.writeAll("Its shape is {\"env\": {");
    for (spec.env, 0..) |key, i| try w.print("{s}\"{s}\": \"…\"", .{ if (i == 0) "" else ", ", key });
    try w.writeAll("}}.\n");
    try w.writeAll(
        "The full format is this package's own manual: `nulya skill list` names it " ++
            "(ext:mcp@<version>/mcp), then `nulya skill load <that ref>`.",
    );
    return out.toOwnedSlice();
}

test "a spec survives a round trip, and an unknown key does not cost the file" {
    const alloc = std.testing.allocator;
    var arena: std.heap.ArenaAllocator = .init(alloc);
    defer arena.deinit();
    const a = arena.allocator();

    const bytes = try encode(a, .{
        .name = "fake",
        .command = "sh",
        .args = &.{"server.sh"},
        .env = &.{"FAKE_TOKEN"},
        .tools = &.{.{ .name = "fake_echo", .tool = "echo" }},
    });
    const back = try decode(a, bytes);
    try std.testing.expectEqualStrings("fake", back.name);
    try std.testing.expectEqualStrings("echo", back.serverTool("fake_echo").?);
    try std.testing.expect(back.serverTool("echo") == null);

    const with_extra = try std.fmt.allocPrint(a, "{{\"later\":true,{s}", .{bytes[1..]});
    const tolerant = try decode(a, with_extra);
    try std.testing.expectEqualStrings("fake", tolerant.name);
}

test "a declared variable with no value is missing, and one with an empty value is too" {
    const alloc = std.testing.allocator;
    var arena: std.heap.ArenaAllocator = .init(alloc);
    defer arena.deinit();
    const a = arena.allocator();

    const spec: Spec = .{ .name = "fake", .env = &.{ "A", "B" } };
    try std.testing.expectEqual(@as(usize, 2), (try missing(a, spec, null)).len);

    var values: std.json.ObjectMap = .empty;
    try values.put(a, "A", .{ .string = "set" });
    try values.put(a, "B", .{ .string = "" });
    const absent = try missing(a, spec, .{ .path = "x", .values = values });
    try std.testing.expectEqual(@as(usize, 1), absent.len);
    try std.testing.expectEqualStrings("B", absent[0]);
}
